### ISSUE TITLE
create AWS VPC for each cndi cluster

### ISSUE THREAD

**Issue by johnstonmatt** [polyseam/cndi#36]
Currently CNDI uses the user's default VPC in AWS when creating a cluster, we want to generate a new VPC for each cluster by generating the required terraform resources in the users `cndi/terraform`

- [x] create terraform resources in HCL
- [x] convert HCL to JSON
- [x] add VPC resource generation to `cndi ow`

**Comment by IamTamika** [comment]
This config works for hcl 
https://github.com/polyseam/terraform-configuration/tree/main/HCL-configuration
