### ISSUE TITLE
create AWS NLB for each cluster

### ISSUE THREAD

**Issue by johnstonmatt** [polyseam/cndi#37]
We want to use Network Load Balancers on AWS so that we can trust an address will always resolve to a target VM, even if the Public IP address of that EC2 instance changes.

- [x] Determine the correct Terraform resource definitions
- [x] Make a JSON representation of the resources if we started with HCL
- [ ] Update `overwrite.ts` to have it generate these resources

**Comment by IamTamika** [comment]
This config works for hcl and creates a nlb
https://github.com/polyseam/terraform-configuration/tree/main/HCL-configuration
