### ISSUE TITLE
[Bug]: EKS Nodes are not tagged with CNDIProject

### ISSUE THREAD

**Issue by johnstonmatt** [polyseam/cndi#431]
### What happened?

All EKS resources should be tagged with `CNDIProject: my-project-name` so they can be properly attributed to a project and prevent accidental deletions.

### Version

cndi v1.12.0
kubeseal v0.21.0
terraform v1.4.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IamTamika** [comment]
[[EKS] [Node Group]: Give EC2 instances a Name tag](https://github.com/aws/containers-roadmap/issues/781)

It hasn't been fixed natively,  there are some workarounds that require more resources
