### ISSUE TITLE
determine minimum IAM role definition and document use of that role

### ISSUE THREAD

**Issue by johnstonmatt** [polyseam/cndi#71]
Currently there is no guidance around the permissions needed to run a CNDI deployment, and we frequently use personal credentials which have many more allowed permissions than are necessary. The account that cndi connects to AWS with should have _only_ the permissions required to do the job.

**Comment by IamTamika** [comment]
Not sure if this is enough
https://docs.google.com/document/d/1Zbe74qOKldsgcFLKjYbiWAXk0yhvoM1UIoGgVgsPooY/edit?usp=sharing

**Comment by johnstonmatt** [comment]
API manager needs to be enabled
